services:
  # FAST API Service
  ## Loads the SQLite database and serves the API
  ## Has access to the ChromaDB Service

  # ChromaDB Service
  ## Provides a vector database for storing and querying embeddings

  # Streamlit Service
  ## Runs the Streamlit app
  ## Connects to the FastAPI service for data retrieval

  # All services are connected via a shared network
