FROM python:3.13-slim-bookworm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# For some reason this package fails on uv add so need to load it beforehand
RUN pip install PyMuPDF==1.26.1

COPY --from=ghcr.io/astral-sh/uv:0.7.13 /uv /uvx /bin/

ADD . /project

WORKDIR /project

# First check if lock file exists and then install dependencies accordingly
RUN if [ -f "uv.lock" ]; then \
        echo "Installing with lock file..." && \
        uv sync --locked; \
    else \
        echo "Lock file not found, installing without it..." && \
        uv sync; \
    fi

# Expose the Streamlit port
EXPOSE 8501

# Run the Streamlit app
CMD ["uv", "run", "streamlit", "run", "/project/src/app.py", "--server.address=0.0.0.0", "--server.port=8501"]
